# Template for storing keys for testing/development. Copy this to secrets.yml in the same directory.

shared:
  teacher_gaming_api_key: 'myapikey'
  sample_student_id: 'mystudentid'
  sample_class_id: 'myclassid'

development:
  secret_key_base: 'mysecretkey'

test:
  secret_key_base: 'mysecretkey'
